In [1]:
import torch

from torch.autograd import Variable

In [2]:
class Model(torch.nn.Module):
    def __init__(self):
        super(Model, self).__init__()
        self.linear = torch.nn.Linear(1,1)
        
    def forward(self, x):
        y_pred = torch.sigmoid(self.linear(x))
        return y_pred

In [3]:
model = Model()

In [4]:
criterion = torch.nn.BCELoss(reduction='elementwise_mean')

In [5]:
optimizer = torch.optim.SGD(model.parameters(), lr = 0.01)

In [6]:
x_data = Variable(torch.Tensor([[1.0], [2.0], [3.0], [4.0]]))
y_data = Variable(torch.Tensor([[0.],[0.],[1.],[1.]]))

In [7]:
for epoch in range(1000):
    y_pred = model(x_data)
    
    loss = criterion(y_pred, y_data)
    print(epoch, loss.data)
    
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

0 tensor(0.6286)
1 tensor(0.6247)
2 tensor(0.6210)
3 tensor(0.6174)
4 tensor(0.6139)
5 tensor(0.6106)
6 tensor(0.6074)
7 tensor(0.6043)
8 tensor(0.6014)
9 tensor(0.5985)
10 tensor(0.5958)
11 tensor(0.5932)
12 tensor(0.5906)
13 tensor(0.5882)
14 tensor(0.5859)
15 tensor(0.5836)
16 tensor(0.5815)
17 tensor(0.5794)
18 tensor(0.5774)
19 tensor(0.5754)
20 tensor(0.5736)
21 tensor(0.5718)
22 tensor(0.5701)
23 tensor(0.5684)
24 tensor(0.5668)
25 tensor(0.5652)
26 tensor(0.5637)
27 tensor(0.5623)
28 tensor(0.5609)
29 tensor(0.5596)
30 tensor(0.5583)
31 tensor(0.5570)
32 tensor(0.5558)
33 tensor(0.5546)
34 tensor(0.5535)
35 tensor(0.5524)
36 tensor(0.5514)
37 tensor(0.5503)
38 tensor(0.5494)
39 tensor(0.5484)
40 tensor(0.5475)
41 tensor(0.5466)
42 tensor(0.5457)
43 tensor(0.5449)
44 tensor(0.5440)
45 tensor(0.5432)
46 tensor(0.5425)
47 tensor(0.5417)
48 tensor(0.5410)
49 tensor(0.5403)
50 tensor(0.5396)
51 tensor(0.5389)
52 tensor(0.5383)
53 tensor(0.5377)
54 tensor(0.5371)
55 tensor(0.5365)
56

639 tensor(0.4362)
640 tensor(0.4361)
641 tensor(0.4359)
642 tensor(0.4358)
643 tensor(0.4357)
644 tensor(0.4356)
645 tensor(0.4354)
646 tensor(0.4353)
647 tensor(0.4352)
648 tensor(0.4351)
649 tensor(0.4349)
650 tensor(0.4348)
651 tensor(0.4347)
652 tensor(0.4346)
653 tensor(0.4344)
654 tensor(0.4343)
655 tensor(0.4342)
656 tensor(0.4341)
657 tensor(0.4339)
658 tensor(0.4338)
659 tensor(0.4337)
660 tensor(0.4336)
661 tensor(0.4334)
662 tensor(0.4333)
663 tensor(0.4332)
664 tensor(0.4331)
665 tensor(0.4329)
666 tensor(0.4328)
667 tensor(0.4327)
668 tensor(0.4326)
669 tensor(0.4324)
670 tensor(0.4323)
671 tensor(0.4322)
672 tensor(0.4321)
673 tensor(0.4320)
674 tensor(0.4318)
675 tensor(0.4317)
676 tensor(0.4316)
677 tensor(0.4315)
678 tensor(0.4313)
679 tensor(0.4312)
680 tensor(0.4311)
681 tensor(0.4310)
682 tensor(0.4308)
683 tensor(0.4307)
684 tensor(0.4306)
685 tensor(0.4305)
686 tensor(0.4304)
687 tensor(0.4302)
688 tensor(0.4301)
689 tensor(0.4300)
690 tensor(0.4299)
691 tensor(0

In [11]:
hour_var = Variable(torch.Tensor([[1.0]]))
print('predict 1 hour ', model(hour_var).data[0][0])

predict 1 hour  tensor(0.3064)


In [12]:
hour_var = Variable(torch.Tensor([[7.0]]))
print('predict 7 hour ', model(hour_var).data[0][0])

predict 7 hour  tensor(0.9868)


In [20]:
model(x_data)

tensor([[0.3064],
        [0.5095],
        [0.7095],
        [0.8517]], grad_fn=<SigmoidBackward>)

In [21]:
model(x_data)[0]

tensor([0.3064], grad_fn=<SelectBackward>)

In [22]:
model(x_data)[0][0]

tensor(0.3064, grad_fn=<SelectBackward>)

In [23]:
x_data

tensor([[1.],
        [2.],
        [3.],
        [4.]])